export const MenuList = [
  {
    name: "Women's Fashion",
    subcategories: {
      Clothing: ["Makeup Kit", "Skincare Products", "Fragrances"],
      Shoes: ["Running Shoes", "Casual Shoes", "Formal Shoes"] ,
      Accessories: ["Handbags", "Sunglasses", "Hats"] ,
      "Traditional Clothing":["Sarees", "Lehengas", "Kurtas"],
      "Women Bags": ["Tote Bags", "Clutches", "Backpacks"],
      "Girls Fashion": ["Dresses", "Tops", "Bottoms"],
      "Lingerie, Sleep & Lounge": ["Bras", "Pajamas", "Nightgowns"],
    },
  },
  {
    name: "Health & Beauty",
    subcategories: [
        {"Skin Care": ["Cleanser", "Moisturizer", "Serum"]},
        {"Makeup": ["Lipstick", "Eyeshadow", "Foundation"]},
        {"Fragrance": ["Perfume", "Cologne", "Body Mist"]},
        {"Bath & Body": ["Shower Gel", "Body Lotion", "Body Scrub"]},
        {"Beauty Tools": ["Makeup Brushes", "Mirrors", "Tweezers"]},
        {"Hair Care": ["Shampoo", "Conditioner", "Hair Oil"]},
        {"Men's Care": ["Shaving Cream", "Aftershave", "Beard Oil"]},
        {"Personal Care": ["Deodorant", "Toothpaste", "Soap"]},
        {"Food Supplements": ["Vitamins", "Protein Powder", "Fish Oil"]},
      ],
  },
  {
    name: "Men's Fashion",
    subcategories: [
        { Clothing: ["T-Shirts", "Jeans", "Jackets"] },
        { Shoes: ["Sneakers", "Boots", "Formal Shoes"] },
        { Accessories: ["Belts", "Ties", "Hats"] },
        { "Mens Bags": ["Backpacks", "Messenger Bags", "Briefcases"] },
        { "Boys Fashion": ["Boys Tops", "Boys Bottoms", "Boys Outerwear"] },
      ],
  },
  {
    name: "Watches & Accessories",
    subcategories: [
        { Watches: ["Luxury Watches", "Sports Watches", "Fashion Watches"] },
        { Jewelry: ["Necklaces", "Bracelets", "Earrings"] },
        { Bags: ["Handbags", "Shoulder Bags", "Clutches"] },
        { "Mens Watches": ["Classic Watches", "Smartwatches", "Dress Watches"] },
        { "Womens Watch": ["Fashion Watches", "Designer Watches", "Smartwatches"] },
        { "Kids Watch": ["Character Watches", "Digital Watches", "Analog Watches"] },
      ],
  },
  {
    name: "Electronic Devices",
    subcategories: [
        { Mobiles: ["iPhone", "Samsung Galaxy", "Google Pixel"] },
        { Laptops: ["Dell XPS", "MacBook Pro", "HP Spectre"] },
        { Cameras: ["Canon EOS", "Sony Alpha", "Nikon D850"] },
        { Smartphones: ["Samsung Galaxy S21", "iPhone 13", "Google Pixel 6"] },
        { "Feature Phones": ["Nokia 3310", "Samsung Guru", "Motorola Razr"] },
        { Tablets: ["iPad Pro", "Samsung Galaxy Tab", "Amazon Fire HD"] },
        { Desktops: ["Dell Inspiron", "HP Pavilion", "Lenovo Ideacentre"] },
        { Printers: ["HP LaserJet", "Epson EcoTank", "Canon PIXMA"] },
        { Moniters: ["Dell Ultrasharp", "LG UltraFine", "ASUS ROG Swift"] },
      ],
  },
  {
    name: "TV & Home Appliances",
    subcategories: [
        { Televisions: ["Sony Bravia 4K", "Samsung QLED", "LG OLED"] },
        { Refrigerators: ["Samsung French Door", "Whirlpool Side-by-Side", "LG InstaView"] },
        { "Washing Machines": ["LG Front Load", "Samsung Top Load", "Whirlpool Semi-Automatic"] },
        { "Large Appliances": ["Dishwashers", "Ovens", "Microwaves"] },
        { "Cooling & Heating": ["Air Conditioners", "Fans", "Heaters"] },
        { "Iron & Garment Care": ["Steam Irons", "Garment Steamers", "Ironing Boards"] },
      ],
  },
  {
    name: "Electronic Accessories",
    subcategories: [
        { Wearable: ["Smartwatches", "Fitness Trackers", "Bluetooth Headphones"] },
        { Chargers: ["USB Chargers", "Wireless Chargers", "Laptop Chargers"] },
        { Cables: ["USB Cables", "Micro USB Cables", "Lightning Cables"] },
        { Audio: ["Headphones", "Earphones", "Bluetooth Speakers"] },
        { "Camera Accessories": ["Camera Bags", "Tripods", "Lens Cleaners"] },
        { Storage: ["External Hard Drives", "Memory Cards", "USB Flash Drives"] },
      ],
  },
  {
    name: "Groceries & Pets",
    subcategories: [
        { "Food Staples": ["Rice", "Flour", "Pasta", "Canned Goods"] },
        { Beverages: ["Tea", "Coffee", "Juices", "Soft Drinks"] },
        { "Pet Supplies": ["Pet Food", "Pet Toys", "Pet Beds", "Pet Grooming"] },
        { "Cooking Ingredients": ["Spices", "Herbs", "Oils", "Sauces"] },
        { "Wines, Beers & Spirits": ["Red Wine", "White Wine", "Craft Beers", "Spirits"] },
        { "Breakfast, Choco & Snacks": ["Cereals", "Chocolate Bars", "Snack Mix", "Granola Bars"] },
      ],
  },
  {
    name: "Babies & Toys",
    subcategories: [
        { "Baby Gear": ["Strollers", "Car Seats", "Baby Carriers", "Playpens"] },
        { Feeding: ["Baby Bottles", "Formula", "Baby Food", "High Chairs"] },
        { "Baby Personal Care": ["Diapers", "Baby Wipes", "Baby Shampoo", "Lotions"] },
        { "Clothing & Accessories": ["Onesies", "Baby Shoes", "Hats", "Blankets"] },
        { "Diapering & Potty": ["Diapers", "Wipes", "Changing Tables", "Potty Seats"] },
        { Nursery: ["Crib Bedding", "Decor", "Night Lights", "Mobiles"] },
      ],
  },
  {
    name: "Home & Lifestyle",
    subcategories: [
        { Furniture: ["Sofas", "Tables", "Chairs", "Bedroom Furniture"] },
        { Decor: ["Wall Art", "Decorative Pillows", "Candles", "Vases"] },
        { Kitchenware: ["Cookware", "Dinnerware", "Utensils", "Appliances"] },
        { Bath: ["Towels", "Shower Curtains", "Bathroom Accessories", "Robes"] },
        { Lighting: ["Table Lamps", "Ceiling Lights", "Floor Lamps", "String Lights"] },
        { "Digital Goods": ["E-books", "Digital Art", "Online Courses", "Software"] },
        { "Musical Instruments": ["Guitars", "Keyboards", "Drums", "Amplifiers"] },
        { "Media, Music & Books": ["Movies", "Music Albums", "Books", "Magazines"] },
        { "Stationery & Craft": ["Notebooks", "Pens", "Art Supplies", "Craft Kits"] },
      ],
  },
  {
    name: "Sports & Outdoor",
    subcategories: [
        { "Mens Shoes and Clothing": ["Running Shoes", "Sports Apparel", "Athletic Socks", "Sportswear Accessories"] },
        { "Outdoor Recreation": ["Camping Gear", "Hiking Equipment", "Backpacks", "Outdoor Clothing"] },
        { "Water Sports": ["Surfboards", "Wetsuits", "Swimwear", "Snorkeling Gear"] },
        { "Team Sports": ["Soccer Gear", "Basketball Equipment", "Football Accessories", "Baseball Gear"] },
        { "Water Bottles": ["Reusable Water Bottles", "Hydration Packs", "Insulated Bottles", "Sport Bottles"] },
      ],
  },
  {
    name: "Motors, Tools & DIY",
    subcategories: [
        { "Automotive": ["Car Accessories", "Car Parts", "Car Care Products", "Vehicle Maintenance Tools"] },
        { "Motorcycles": ["Motorcycle Parts", "Motorcycle Accessories", "Motorcycle Gear", "Helmets", "Gloves"] },
        { "Auto Care": ["Cleaning Supplies", "Car Wash Kits", "Polishing Products", "Waxing Kits"] },
        { "Helmets": ["Full-Face Helmets", "Open-Face Helmets", "Modular Helmets", "Dual Sport Helmets"] },
        { "Gloves": ["Mechanic Gloves", "Motorcycle Gloves", "Work Gloves"] },
        { "Auto Electronics": ["Car Audio Systems", "GPS Devices", "Dash Cams", "Vehicle Security Systems"] },
      ],
  },
];
