import { Box, Card, Typography } from "@mui/material";
import React from "react";
import Footer2 from "../footer/Footer2";

const TermOfUse = () => {
  return (
    <>
      <Box style={{ marginTop: "5rem",textAlign: 'justify' }}>
        <Typography variant="h2" style={{ fontSize: "32px" }}>
          Terms and Conditions
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "12px" }}
        >
          Please read the Terms and Conditions carefully before using
          Daraz.com.np.
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "12px" }}
        >
          This electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", fontWeight: "bold" }}
        >
          1. INTRODUCTION
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          Welcome to Daraz.com.np also hereby known as “we", "us" or "Daraz". We
          are an online marketplace and these are the terms and conditions
          governing your access and use of Daraz along with its related
          sub-domains, sites, mobile app, services and tools (the "Site"). By
          using the Site, you hereby accept these terms and conditions
          (including the linked information herein) and represent that you agree
          to comply with these terms and conditions (the "User Agreement"). This
          User Agreement is deemed effective upon your use of the Site which
          signifies your acceptance of these terms. If you do not agree to be
          bound by this User Agreement please do not access, register with or
          use this Site. This site is owned and operated by Daraz Kaymu Private
          Limited (Registration No.125263/71/72).
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          The Site reserves the right to change, modify, add, or remove portions
          of these Terms and Conditions at any time without any prior
          notification. Changes will be effective when posted on the Site with
          no other notice provided. Please check these Terms and Conditions
          regularly for updates. Your continued use of the Site following the
          posting of changes to Terms and Conditions of use constitutes your
          acceptance of those changes.
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", fontWeight: "bold" }}
        >
          2. CONDITIONS OF USE
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", marginTop: "16px", fontWeight: "bold" }}
        >
          A. YOUR ACCOUNT
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          To access certain services offered by the platform, we may require
          that you create an account with us or provide personal information to
          complete the creation of an account. We may at any time in our sole
          and absolute discretion, invalidate the username and/or password
          without giving any reason or prior notice and shall not be liable or
          responsible for any losses suffered by, caused by, arising out of, in
          connection with or by reason of such request or invalidation.
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          You are responsible for maintaining the confidentiality of your user
          identification, password, account details and related private
          information. You agree to accept this responsibility and ensure your
          account and its related details are maintained securely at all times
          and all necessary steps are taken to prevent misuse of your account.
          You should inform us immediately if you have any reason to believe
          that your password has become known to anyone else, or if the password
          is being, or is likely to be, used in an unauthorized manner. You
          agree and acknowledge that any use of the Site and related services
          offered and/or any access to private information, data or
          communications using your account and password shall be deemed to be
          either performed by you or authorized by you as the case may be. You
          agree to be bound by any access of the Site and/or use of any services
          offered by the Site (whether such access or use are authorized by you
          or not). You agree that we shall be entitled (but not obliged) to act
          upon, rely on or hold you solely responsible and liable in respect
          thereof as if the same were carried out or transmitted by you. You
          further agree and acknowledge that you shall be bound by and agree to
          fully indemnify us against any and all losses arising from the use of
          or access to the Site through your account.
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          Please ensure that the details you provide us with are correct and
          complete at all times. You are obligated to update details about your
          account in real time by accessing your account online. For pieces of
          information you are not able to update by accessing Your Account on
          the Site, you must inform us via our customer service communication
          channels to assist you with these changes. We reserve the right to
          refuse access to the Site, terminate accounts, remove or edit content
          at any time without prior notice to you. We may at any time in our
          sole and absolute discretion, request that you update your Personal
          Data or forthwith invalidate the account or related details without
          giving any reason or prior notice and shall not be liable or
          responsible for any losses suffered by or caused by you or arising out
          of or in connection with or by reason of such request or invalidation.
          You hereby agree to change your password from time to time and to keep
          your account secure and also shall be responsible for the
          confidentiality of your account and liable for any disclosure or use
          (whether such use is authorised or not) of the username and/or
          password.
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", fontWeight: "bold" }}
        >
          B. PRIVACY
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          Please review our Privacy Agreement, which also governs your visit to
          the Site. The personal information / data provided to us by you or
          your use of the Site will be treated as strictly confidential, in
          accordance with the Privacy Agreement and applicable laws and
          regulations. If you object to your information being transferred or
          used in the manner specified in the Privacy Agreement, please do not
          use the Site.
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", fontWeight: "bold" }}
        >
          C. PLATFORM FOR COMMUNICATION
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          You agree, understand and acknowledge that the Site is an online
          platform that enables you to purchase products listed at the price
          indicated therein at any time from any location using a payment method
          of your choice ( Daraz may charge you a fee for choosing various
          options available on the platform). You further agree and acknowledge
          that we are only a facilitator and cannot be a party to or control in
          any manner any transactions on the Site or on a payment gateway as
          made available to you by an independent service provider. Accordingly,
          the contract of sale of products on the Site shall be a strictly
          bipartite contract between you and the sellers on our Site while the
          payment processing occurs between you, the service provider and in
          case of prepayments with electronic cards your issuer bank.
          Accordingly, the contract of payment on the Site shall be strictly a
          bipartite contract between you and the service provider as listed on
          our Site.
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", fontWeight: "bold" }}
        >
          D. CONTINUED AVAILABILITY OF THE SITE
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          We will do our utmost to ensure that access to the Site is
          consistently available and is uninterrupted and error-free. However,
          due to the nature of the Internet and the nature of the Site, this
          cannot be guaranteed. Additionally, your access to the Site may also
          be occasionally suspended or restricted to allow for repairs,
          maintenance, or the introduction of new facilities or services at any
          time without prior notice. We will attempt to limit the frequency and
          duration of any such suspension or restriction.
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", fontWeight: "bold" }}
        >
          E. LICENSE TO ACCESS THE SITE
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          We require that by accessing the Site, you confirm that you can form
          legally binding contracts and therefore you confirm that you are at
          least 18 years of age or are accessing the Site under the supervision
          of a parent or legal guardian. We grant you a non-transferable,
          revocable and non-exclusive license to use the Site, in accordance
          with the Terms and Conditions described herein, for the purposes of
          shopping for personal items and services as listed to be sold on the
          Site. Commercial use or use on behalf of any third party is
          prohibited, except as explicitly permitted by us in advance. If you
          are registering as a business entity, you represent that you have the
          authority to bind that entity to this User Agreement and that you and
          the business entity will comply with all applicable laws relating to
          online trading. No person or business entity may register as a member
          of the Site more than once. Any breach of these Terms and Conditions
          shall result in the immediate revocation of the license granted in
          this paragraph without notice to you.
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          Content provided on this Site is solely for informational purposes.
          Product representations including price, available stock, features,
          add-ons and any other details as expressed on this Site are the
          responsibility of the vendors displaying them and is not guaranteed as
          completely accurate by us. Submissions or opinions expressed on this
          Site are those of the individual(s) posting such content and may not
          reflect our opinions.
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          We grant you a limited license to access and make personal use of this
          Site, but not to download (excluding page caches) or modify the Site
          or any portion of it in any manner. This license does not include any
          resale or commercial use of this Site or its contents; any collection
          and use of any product listings, descriptions, or prices; any
          derivative use of this Site or its contents; any downloading or
          copying of account information for the benefit of another seller; or
          any use of data mining, robots, or similar data gathering and
          extraction tools.
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          This Site or any portion of it (including but not limited to any
          copyrighted material, trademarks, or other proprietary information)
          may not be reproduced, duplicated, copied, sold, resold, visited,
          distributed or otherwise exploited for any commercial purpose without
          express written consent by us as may be applicable.
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", marginTop: "16px", fontWeight: "bold" }}
        >
          F. YOUR CONDUCT
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          To access certain services offered by the platform, we may require
          that you create an account with us or provide personal information to
          complete the creation of an account. We may at any time in our sole
          and absolute discretion, invalidate the username and/or password
          without giving any reason or prior notice and shall not be liable or
          responsible for any losses suffered by, caused by, arising out of, in
          connection with or by reason of such request or invalidation.
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          You are responsible for maintaining the confidentiality of your user
          identification, password, account details and related private
          information. You agree to accept this responsibility and ensure your
          account and its related details are maintained securely at all times
          and all necessary steps are taken to prevent misuse of your account.
          You should inform us immediately if you have any reason to believe
          that your password has become known to anyone else, or if the password
          is being, or is likely to be, used in an unauthorized manner. You
          agree and acknowledge that any use of the Site and related services
          offered and/or any access to private information, data or
          communications using your account and password shall be deemed to be
          either performed by you or authorized by you as the case may be. You
          agree to be bound by any access of the Site and/or use of any services
          offered by the Site (whether such access or use are authorized by you
          or not). You agree that we shall be entitled (but not obliged) to act
          upon, rely on or hold you solely responsible and liable in respect
          thereof as if the same were carried out or transmitted by you. You
          further agree and acknowledge that you shall be bound by and agree to
          fully indemnify us against any and all losses arising from the use of
          or access to the Site through your account.
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          Please ensure that the details you provide us with are correct and
          complete at all times. You are obligated to update details about your
          account in real time by accessing your account online. For pieces of
          information you are not able to update by accessing Your Account on
          the Site, you must inform us via our customer service communication
          channels to assist you with these changes. We reserve the right to
          refuse access to the Site, terminate accounts, remove or edit content
          at any time without prior notice to you. We may at any time in our
          sole and absolute discretion, request that you update your Personal
          Data or forthwith invalidate the account or related details without
          giving any reason or prior notice and shall not be liable or
          responsible for any losses suffered by or caused by you or arising out
          of or in connection with or by reason of such request or invalidation.
          You hereby agree to change your password from time to time and to keep
          your account secure and also shall be responsible for the
          confidentiality of your account and liable for any disclosure or use
          (whether such use is authorised or not) of the username and/or
          password.
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", fontWeight: "bold" }}
        >
          G. YOUR SUBMISSION
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          Please review our Privacy Agreement, which also governs your visit to
          the Site. The personal information / data provided to us by you or
          your use of the Site will be treated as strictly confidential, in
          accordance with the Privacy Agreement and applicable laws and
          regulations. If you object to your information being transferred or
          used in the manner specified in the Privacy Agreement, please do not
          use the Site.
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", fontWeight: "bold" }}
        >
          H. CLAIMS AGAINST OBJECTIONABLE CONTENT
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          You agree, understand and acknowledge that the Site is an online
          platform that enables you to purchase products listed at the price
          indicated therein at any time from any location using a payment method
          of your choice ( Daraz may charge you a fee for choosing various
          options available on the platform). You further agree and acknowledge
          that we are only a facilitator and cannot be a party to or control in
          any manner any transactions on the Site or on a payment gateway as
          made available to you by an independent service provider. Accordingly,
          the contract of sale of products on the Site shall be a strictly
          bipartite contract between you and the sellers on our Site while the
          payment processing occurs between you, the service provider and in
          case of prepayments with electronic cards your issuer bank.
          Accordingly, the contract of payment on the Site shall be strictly a
          bipartite contract between you and the service provider as listed on
          our Site.
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", fontWeight: "bold" }}
        >
          I. CLAIMS AGAINST INFRINGING CONTENT
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          We will do our utmost to ensure that access to the Site is
          consistently available and is uninterrupted and error-free. However,
          due to the nature of the Internet and the nature of the Site, this
          cannot be guaranteed. Additionally, your access to the Site may also
          be occasionally suspended or restricted to allow for repairs,
          maintenance, or the introduction of new facilities or services at any
          time without prior notice. We will attempt to limit the frequency and
          duration of any such suspension or restriction.
        </Typography>
        <Typography
          variant="h2"
          style={{ fontSize: "16px", fontWeight: "bold" }}
        >
          J. TRADEMARKS AND COPYRIGHTS
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          We require that by accessing the Site, you confirm that you can form
          legally binding contracts and therefore you confirm that you are at
          least 18 years of age or are accessing the Site under the supervision
          of a parent or legal guardian. We grant you a non-transferable,
          revocable and non-exclusive license to use the Site, in accordance
          with the Terms and Conditions described herein, for the purposes of
          shopping for personal items and services as listed to be sold on the
          Site. Commercial use or use on behalf of any third party is
          prohibited, except as explicitly permitted by us in advance. If you
          are registering as a business entity, you represent that you have the
          authority to bind that entity to this User Agreement and that you and
          the business entity will comply with all applicable laws relating to
          online trading. No person or business entity may register as a member
          of the Site more than once. Any breach of these Terms and Conditions
          shall result in the immediate revocation of the license granted in
          this paragraph without notice to you.
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          Content provided on this Site is solely for informational purposes.
          Product representations including price, available stock, features,
          add-ons and any other details as expressed on this Site are the
          responsibility of the vendors displaying them and is not guaranteed as
          completely accurate by us. Submissions or opinions expressed on this
          Site are those of the individual(s) posting such content and may not
          reflect our opinions.
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          We grant you a limited license to access and make personal use of this
          Site, but not to download (excluding page caches) or modify the Site
          or any portion of it in any manner. This license does not include any
          resale or commercial use of this Site or its contents; any collection
          and use of any product listings, descriptions, or prices; any
          derivative use of this Site or its contents; any downloading or
          copying of account information for the benefit of another seller; or
          any use of data mining, robots, or similar data gathering and
          extraction tools.
        </Typography>
        <Typography
          style={{ fontSize: "14px", marginTop: "12px", marginBottom: "24px" }}
        >
          This Site or any portion of it (including but not limited to any
          copyrighted material, trademarks, or other proprietary information)
          may not be reproduced, duplicated, copied, sold, resold, visited,
          distributed or otherwise exploited for any commercial purpose without
          express written consent by us as may be applicable.
        </Typography>
        <Footer2 />
      </Box>
    </>
  );
};

export default TermOfUse;
